// Auto generated by utensor-cli

#include "src/uTensor/core/context.hpp"
#include "src/uTensor/core/tensor.hpp"
#include "src/uTensor/ops/ArrayOps.hpp"
#include "add_graph.hpp"
#include "src/uTensor/ops/MathOps.hpp"
#include "src/uTensor/loaders/tensorIdxImporter.hpp"


void get_add_graph_ctx(Context& ctx) {
{
    TensorIdxImporter t_import;
    ctx.add(t_import.float_import("/fs/constants/add_graph/x_0.idx"),
            "x:0",
            2);
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.int_import("/fs/constants/add_graph/z_eightbit_x__port__0_reshape_dims_0.idx"),
            "z_eightbit/x__port__0/reshape_dims:0",
            1);
}
{
    ctx.add(new RamTensor<float>(), "z_eightbit/x__port__0/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "x:0", "z_eightbit/x__port__0/reshape_dims:0" },
             { "z_eightbit/x__port__0/reshape:0" });
    ctx.eval();
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.int_import("/fs/constants/add_graph/z_eightbit_x__port__0_reduction_dims_0.idx"),
            "z_eightbit/x__port__0/reduction_dims:0",
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "z_eightbit/x__port__0/min:0", 1);
    ctx.push(new MinOp(), 
             { "z_eightbit/x__port__0/reshape:0", "z_eightbit/x__port__0/reduction_dims:0" },
             { "z_eightbit/x__port__0/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "z_eightbit/x__port__0/max:0", 1);
    ctx.push(new MaxOp(), 
             { "z_eightbit/x__port__0/reshape:0", "z_eightbit/x__port__0/reduction_dims:0" },
             { "z_eightbit/x__port__0/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "z_eightbit/x__port__0/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "z_eightbit/x__port__0/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "z_eightbit/x__port__0/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "x:0",  "z_eightbit/x__port__0/min:0", "z_eightbit/x__port__0/max:0" },
             {  "z_eightbit/x__port__0/quantize:0",  "z_eightbit/x__port__0/quantize:1", "z_eightbit/x__port__0/quantize:2" });
    ctx.eval();
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.float_import("/fs/constants/add_graph/y_0.idx"),
            "y:0",
            2);
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.int_import("/fs/constants/add_graph/z_eightbit_y__port__0_reshape_dims_0.idx"),
            "z_eightbit/y__port__0/reshape_dims:0",
            1);
}
{
    ctx.add(new RamTensor<float>(), "z_eightbit/y__port__0/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "y:0", "z_eightbit/y__port__0/reshape_dims:0" },
             { "z_eightbit/y__port__0/reshape:0" });
    ctx.eval();
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.int_import("/fs/constants/add_graph/z_eightbit_y__port__0_reduction_dims_0.idx"),
            "z_eightbit/y__port__0/reduction_dims:0",
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "z_eightbit/y__port__0/min:0", 1);
    ctx.push(new MinOp(), 
             { "z_eightbit/y__port__0/reshape:0", "z_eightbit/y__port__0/reduction_dims:0" },
             { "z_eightbit/y__port__0/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "z_eightbit/y__port__0/max:0", 1);
    ctx.push(new MaxOp(), 
             { "z_eightbit/y__port__0/reshape:0", "z_eightbit/y__port__0/reduction_dims:0" },
             { "z_eightbit/y__port__0/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "z_eightbit/y__port__0/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "z_eightbit/y__port__0/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "z_eightbit/y__port__0/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "y:0",  "z_eightbit/y__port__0/min:0", "z_eightbit/y__port__0/max:0" },
             {  "z_eightbit/y__port__0/quantize:0",  "z_eightbit/y__port__0/quantize:1", "z_eightbit/y__port__0/quantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<int>(), "z/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "z/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "z/eightbit:2", 2);
    ctx.push(new QuantizedAddOp<uint8_t, uint8_t, int>(), 
             { "z_eightbit/x__port__0/quantize:0", "z_eightbit/x__port__0/quantize:1", "z_eightbit/x__port__0/quantize:2", "z_eightbit/y__port__0/quantize:0", "z_eightbit/y__port__0/quantize:1",  "z_eightbit/y__port__0/quantize:2" },
             { "z/eightbit:0", "z/eightbit:1",  "z/eightbit:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>({1}), "z/eightbit/requant_range:0", 1);
    ctx.add(new RamTensor<float>({1}), "z/eightbit/requant_range:1", 1);
    ctx.push(new Requantization_RangeOp(),
             { "z/eightbit:0", "z/eightbit:1", "z/eightbit:2" },
             { "z/eightbit/requant_range:0", "z/eightbit/requant_range:1" });
    ctx.eval();
}
{   
    ctx.add(new RamTensor<uint8_t>(), "z/eightbit/requantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "z/eightbit/requantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "z/eightbit/requantize:2", 1);
    ctx.push(new RequantizeOp(),
             { "z/eightbit:0", "z/eightbit:1", "z/eightbit:2", "z/eightbit/requant_range:0", "z/eightbit/requant_range:1" },
             { "z/eightbit/requantize:0", "z/eightbit/requantize:1", "z/eightbit/requantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>(), "z:0");
    ctx.push(new DequantizeOp(), 
             { "z/eightbit/requantize:0", "z/eightbit/requantize:1", "z/eightbit/requantize:2" },
             { "z:0" });
}
}
