// Auto generated by utensor-cli

#ifndef __MODELS_TEST_QUANTIZED_ADD_H
#define __MODELS_TEST_QUANTIZED_ADD_H
#include "uTensor/core/context.hpp"
void get_test_quantized_add_ctx(Context& ctx);
#endif // __MODELS_TEST_QUANTIZED_ADD_H