// Auto generated by utensor-cli

#include <stdint.h>

const float inline_ref_3_0 [ 10 ] = {  0.2570402,  0.58795494,  0.16498376,  0.1834913,  0.7072938,  0.03855189,  0.21099372,  0.23439807,  0.36095497,  0.2187462,  };
#include <stdint.h>

const float inline_a_3_0 [ 10 ] = {  0.3582354,  0.6139192,  0.4303863,  0.3630436,  0.80719084,  0.8000849,  0.24496628,  0.95068,  0.60737497,  0.4648891,  };
#include <stdint.h>

const int inline_c_3_eightbit_a_3__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_c_3_eightbit_a_3__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_b_3_0 [ 10 ] = {  0.7175176,  0.95770735,  0.38333878,  0.505425,  0.87624115,  0.04818475,  0.8613174,  0.24655832,  0.59428686,  0.47053415,  };
#include <stdint.h>

const int inline_c_3_eightbit_b_3__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_c_3_eightbit_b_3__port__0_reduction_dims_0 [ 1 ] = {  0,  };
