// Auto generated by utensor-cli

#ifndef __MODELS_ADD_GRAPH_H
#define __MODELS_ADD_GRAPH_H
#include "src/uTensor/core/context.hpp"
void get_add_graph_ctx(Context& ctx);
#endif // __MODELS_ADD_GRAPH_H
