/* Auto-generated by utensor cli */
#ifndef __TANH_MODEL_INTERFACE_H
#define __TANH_MODEL_INTERFACE_H
#include "uTensor.h"

using namespace uTensor;

class TanhModel : public ModelInterface<1, 1> 
{
 public:
  enum input_names : uint8_t { input_0 };
  enum output_names : uint8_t { output_0 };
  TanhModel();
 protected:
  virtual void compute();
 private:
  // Operators
  ReferenceOperators::TanhOperator<int8_t, int8_t> op_TanhOperator_000;

  TflmSymQuantOps::DequantizeOperator<float, int8_t> op_DequantizeOperator_001;

  TflmSymQuantOps::QuantizeOperator<int8_t, float> op_QuantizeOperator_002;

  // memory allocators
  localCircularArenaAllocator<3640, uint16_t> ram_allocator;
  localCircularArenaAllocator<256, uint16_t> metadata_allocator;
};

#endif // __TANH_MODEL_INTERFACE_H