// Auto generated by utensor-cli

#ifndef __MODELS_MNIST_FOR_UTENSOR_H
#define __MODELS_MNIST_FOR_UTENSOR_H
#include "uTensor/core/context.hpp"
void get_mnist_for_uTensor_ctx(Context& ctx);
#endif // __MODELS_MNIST_FOR_UTENSOR_H