// Auto generated by utensor-cli

#include "qmul4.hpp"
#include "uTensor/core/context.hpp"
#include "uTensor/ops/MathOps.hpp"
#include "uTensor/core/tensor.hpp"
#include "qmul4_weight.hpp"
#include "uTensor/ops/ArrayOps.hpp"


void get_qmul4_ctx(Context& ctx) {
{    
    ctx.add(new BinaryTensor<float>({10}, inline_ref_4_0), 
            "ref_4:0");
}
{    
    ctx.add(new BinaryTensor<float>({10}, inline_Const_0), 
            "Const:0", 
            2);
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_c_4_eightbit_Const__port__0_reshape_dims_0), 
            "c_4_eightbit/Const__port__0/reshape_dims:0", 
            1);
}
{
    ctx.add(new RamTensor<float>(), "c_4_eightbit/Const__port__0/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "Const:0", "c_4_eightbit/Const__port__0/reshape_dims:0" },
             { "c_4_eightbit/Const__port__0/reshape:0" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_c_4_eightbit_Const__port__0_reduction_dims_0), 
            "c_4_eightbit/Const__port__0/reduction_dims:0", 
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "c_4_eightbit/Const__port__0/min:0", 1);
    ctx.push(new MinOp(), 
             { "c_4_eightbit/Const__port__0/reshape:0", "c_4_eightbit/Const__port__0/reduction_dims:0" },
             { "c_4_eightbit/Const__port__0/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "c_4_eightbit/Const__port__0/max:0", 1);
    ctx.push(new MaxOp(), 
             { "c_4_eightbit/Const__port__0/reshape:0", "c_4_eightbit/Const__port__0/reduction_dims:0" },
             { "c_4_eightbit/Const__port__0/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "c_4_eightbit/Const__port__0/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "c_4_eightbit/Const__port__0/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "c_4_eightbit/Const__port__0/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "Const:0",  "c_4_eightbit/Const__port__0/min:0", "c_4_eightbit/Const__port__0/max:0" },
             {  "c_4_eightbit/Const__port__0/quantize:0",  "c_4_eightbit/Const__port__0/quantize:1", "c_4_eightbit/Const__port__0/quantize:2" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<float>({10}, inline_Const_1_0), 
            "Const_1:0", 
            2);
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_c_4_eightbit_Const_1__port__0_reshape_dims_0), 
            "c_4_eightbit/Const_1__port__0/reshape_dims:0", 
            1);
}
{
    ctx.add(new RamTensor<float>(), "c_4_eightbit/Const_1__port__0/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "Const_1:0", "c_4_eightbit/Const_1__port__0/reshape_dims:0" },
             { "c_4_eightbit/Const_1__port__0/reshape:0" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_c_4_eightbit_Const_1__port__0_reduction_dims_0), 
            "c_4_eightbit/Const_1__port__0/reduction_dims:0", 
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "c_4_eightbit/Const_1__port__0/min:0", 1);
    ctx.push(new MinOp(), 
             { "c_4_eightbit/Const_1__port__0/reshape:0", "c_4_eightbit/Const_1__port__0/reduction_dims:0" },
             { "c_4_eightbit/Const_1__port__0/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "c_4_eightbit/Const_1__port__0/max:0", 1);
    ctx.push(new MaxOp(), 
             { "c_4_eightbit/Const_1__port__0/reshape:0", "c_4_eightbit/Const_1__port__0/reduction_dims:0" },
             { "c_4_eightbit/Const_1__port__0/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "c_4_eightbit/Const_1__port__0/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "c_4_eightbit/Const_1__port__0/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "c_4_eightbit/Const_1__port__0/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "Const_1:0",  "c_4_eightbit/Const_1__port__0/min:0", "c_4_eightbit/Const_1__port__0/max:0" },
             {  "c_4_eightbit/Const_1__port__0/quantize:0",  "c_4_eightbit/Const_1__port__0/quantize:1", "c_4_eightbit/Const_1__port__0/quantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<int>(), "c_4/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "c_4/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "c_4/eightbit:2", 2);
    ctx.push(new QuantizedMulOp<uint8_t, uint8_t, int>(), 
             { "c_4_eightbit/Const__port__0/quantize:0", "c_4_eightbit/Const__port__0/quantize:1", "c_4_eightbit/Const__port__0/quantize:2", "c_4_eightbit/Const_1__port__0/quantize:0", "c_4_eightbit/Const_1__port__0/quantize:1",  "c_4_eightbit/Const_1__port__0/quantize:2" },
             { "c_4/eightbit:0", "c_4/eightbit:1",  "c_4/eightbit:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>({1}), "c_4/eightbit/requant_range:0", 1);
    ctx.add(new RamTensor<float>({1}), "c_4/eightbit/requant_range:1", 1);
    ctx.push(new Requantization_RangeOp(),
             { "c_4/eightbit:0", "c_4/eightbit:1", "c_4/eightbit:2" },
             { "c_4/eightbit/requant_range:0", "c_4/eightbit/requant_range:1" });
    ctx.eval();
}
{   
    ctx.add(new RamTensor<uint8_t>(), "c_4/eightbit/requantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "c_4/eightbit/requantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "c_4/eightbit/requantize:2", 1);
    ctx.push(new RequantizeOp(),
             { "c_4/eightbit:0", "c_4/eightbit:1", "c_4/eightbit:2", "c_4/eightbit/requant_range:0", "c_4/eightbit/requant_range:1" },
             { "c_4/eightbit/requantize:0", "c_4/eightbit/requantize:1", "c_4/eightbit/requantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>(), "c_4:0");
    ctx.push(new DequantizeOp(), 
             { "c_4/eightbit/requantize:0", "c_4/eightbit/requantize:1", "c_4/eightbit/requantize:2" },
             { "c_4:0" });
}
}