// Auto generated by utensor-cli

#include <stdint.h>

const float inline_ref_3_0 [ 10 ] = {  0.07685813,  0.67876655,  0.3237661,  0.17137085,  0.16386311,  0.39541134,  0.071583964,  0.40870044,  0.1638737,  0.7686936,  };
#include <stdint.h>

const float inline_Const_0 [ 10 ] = {  0.6593772,  0.9346317,  0.8566355,  0.6036473,  0.6542604,  0.5076212,  0.08516219,  0.6785715,  0.5295614,  0.8948599,  };
#include <stdint.h>

const int inline_c_3_eightbit_Const__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_c_3_eightbit_Const__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_Const_1_0 [ 10 ] = {  0.1165617,  0.72623956,  0.37795085,  0.28389236,  0.2504555,  0.77894956,  0.8405604,  0.6022953,  0.30945176,  0.85901004,  };
#include <stdint.h>

const int inline_c_3_eightbit_Const_1__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_c_3_eightbit_Const_1__port__0_reduction_dims_0 [ 1 ] = {  0,  };
