// Auto generated by utensor-cli

#include <stdint.h>

const float inline_ref_0_0 [ 10 ] = {  0.0,  1.0,  4.0,  9.0,  16.0,  25.0,  36.0,  49.0,  64.0,  81.0,  };
#include <stdint.h>

const float inline_a_0_0 [ 10 ] = {  0.0,  1.0,  2.0,  3.0,  4.0,  5.0,  6.0,  7.0,  8.0,  9.0,  };
#include <stdint.h>

const int inline_c_0_eightbit_a_0__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_c_0_eightbit_a_0__port__0_reduction_dims_0 [ 1 ] = {  0,  };
