// Auto generated by utensor-cli

#include <stdint.h>

const float inline_ref_2_0 [ 10 ] = {  0.6896683,  0.4677817,  0.037431896,  0.3421395,  0.0675253,  0.06448344,  0.6730276,  0.34713995,  0.31741098,  0.59473324,  };
#include <stdint.h>

const float inline_Const_0 [ 10 ] = {  0.72340065,  0.8586901,  0.16552326,  0.743063,  0.3728834,  0.18324934,  0.7364515,  0.35831743,  0.32619113,  0.971608,  };
#include <stdint.h>

const int inline_c_2_eightbit_Const__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_c_2_eightbit_Const__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_Const_1_0 [ 10 ] = {  0.95336974,  0.54476196,  0.22614282,  0.46044484,  0.18108958,  0.35188907,  0.913879,  0.9688057,  0.9730828,  0.61211234,  };
#include <stdint.h>

const int inline_c_2_eightbit_Const_1__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_c_2_eightbit_Const_1__port__0_reduction_dims_0 [ 1 ] = {  0,  };
