// Auto generated by utensor-cli

#include <stdint.h>

const float inline_ref_1_0 [ 10 ] = {  0.011775053,  0.08381592,  0.7292312,  0.104419865,  0.37275904,  0.033528745,  0.1564582,  0.5619677,  0.11846019,  0.44154587,  };
#include <stdint.h>

const float inline_Const_0 [ 10 ] = {  0.0403968,  0.13075379,  0.9847866,  0.28699195,  0.5964773,  0.66051394,  0.7144502,  0.60733473,  0.99221176,  0.5193309,  };
#include <stdint.h>

const int inline_c_1_eightbit_Const__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_c_1_eightbit_Const__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_Const_1_0 [ 10 ] = {  0.2914848,  0.64102095,  0.74049664,  0.3638425,  0.62493414,  0.050761603,  0.21899106,  0.92530143,  0.11939003,  0.8502207,  };
#include <stdint.h>

const int inline_c_1_eightbit_Const_1__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_c_1_eightbit_Const_1__port__0_reduction_dims_0 [ 1 ] = {  0,  };
