// Auto generated by utensor-cli

#include <stdint.h>

const float inline_ref_4_0 [ 10 ] = {  0.5603306,  0.59643817,  0.12815967,  0.24403676,  0.015129619,  0.27278113,  0.032641824,  0.078685574,  0.09874684,  0.2066942,  };
#include <stdint.h>

const float inline_a_4_0 [ 10 ] = {  0.7128955,  0.6213143,  0.465173,  0.36555701,  0.08588739,  0.37936696,  0.2645608,  0.25818077,  0.5931487,  0.3813792,  };
#include <stdint.h>

const int inline_c_4_eightbit_a_4__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_c_4_eightbit_a_4__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_b_4_0 [ 10 ] = {  0.7859926,  0.9599621,  0.2755097,  0.6675751,  0.17615648,  0.7190429,  0.12338119,  0.3047693,  0.16647907,  0.54196507,  };
#include <stdint.h>

const int inline_c_4_eightbit_b_4__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_c_4_eightbit_b_4__port__0_reduction_dims_0 [ 1 ] = {  0,  };
