// Auto generated by utensor-cli

#include <stdint.h>

const float inline_ref_4_0 [ 10 ] = {  0.062311757,  0.13624997,  0.16564575,  0.10716134,  0.82672673,  0.045899965,  0.39640954,  0.7465527,  0.004251618,  0.51629525,  };
#include <stdint.h>

const float inline_Const_0 [ 10 ] = {  0.18993436,  0.15156911,  0.87196773,  0.44288573,  0.87609684,  0.05050894,  0.4924413,  0.7715238,  0.20615304,  0.80710316,  };
#include <stdint.h>

const int inline_c_4_eightbit_Const__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_c_4_eightbit_Const__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_Const_1_0 [ 10 ] = {  0.32806996,  0.8989297,  0.18996775,  0.24196161,  0.9436477,  0.90874934,  0.80498844,  0.9676341,  0.020623602,  0.63968927,  };
#include <stdint.h>

const int inline_c_4_eightbit_Const_1__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_c_4_eightbit_Const_1__port__0_reduction_dims_0 [ 1 ] = {  0,  };
